---
title: Jesus' End-Time Timeline - What Sign Will Signal Your Return
date: 2017-10-24
description: "Jesus' Response To The Disciples' 2nd Question - What Sign Will Signal Your Return?"  
categories: [End-Times Timeline, End of the World, Jesus' Return, Matthew 24, Signs]
---

---

## What Is Jesus' End-Time Timeline

### What Sign Will Signal Your Return?

This is part 2 of Jesus' End-Time Timeline as documented in Matthew 24. This article covers Jesus' response to the disciples' second question in Matthew 24:3 - "**What Sign Will Signal Your Return?**"

- Abomination of Desolation In Temple
- Worst Anguish Ever To Be Seen
- Time of Calamity Shortened For The Sake Of The Elect
- Miracle Working False Messiahs and False Prophets
- **Strong** Deception
- His Coming Is As Lightning

> Mat 24:15 NLT - "**The day is coming** when you will see what Daniel the prophet spoke about--the sacrilegious object that causes desecration standing in the Holy Place." (Reader, pay attention!)
> 
> Mat 24:16 NLT - "**Then** those in Judea must flee to the hills.
> 
> Mat 24:17 NLT - A person out on the deck of a roof must not go down into the house to pack.
> 
> Mat 24:18 NLT - A person out in the field must not return even to get a coat.
> 
> Mat 24:19 NLT - How terrible it will be for pregnant women and for nursing mothers in those days.
> 
> Mat 24:20 NLT - And pray that your flight will not be in winter or on the Sabbath.

Luke 21 adds the following perspective ...

- Jerusalem Surrounded By Armies
- Days Of God's Vengeance
- Disaster In The Land \[of Israel\]
- Great Anger Against Israel
- People Killed or Taken Captive
- Jerusalem Trampled Down By Gentiles - Time Of The Gentiles

> Luk 21:20 NLT - "And when you see Jerusalem surrounded by armies, then you will know that the time of its destruction has arrived.
> 
> Luk 21:21 NLT - Then those in Judea must flee to the hills. Those in Jerusalem must get out, and those out in the country should not return to the city.
> 
> Luk 21:22 NLT - For **those will be days of God's vengeance**, and the prophetic words of the Scriptures will be fulfilled.
> 
> Luk 21:23 NLT - How terrible it will be for pregnant women and for nursing mothers in those days. For there will be disaster in the land and great anger against this people.
> 
> Luk 21:24 NLT - They will be killed by the sword or sent away as captives to all the nations of the world. And Jerusalem will be trampled down by the Gentiles until the period of the Gentiles comes to an end.

Back to Matthew 24 ...

> Mat 24:21 NLT - For there will be greater anguish than at any time since the world began**.** And it will never be so great again.
> 
> Mat 24:22 NLT - In fact, unless that time of calamity is shortened, not a single person will survive**.** But it will be shortened for the sake of God's chosen ones.
> 
> Mat 24:23 NLT - "**Then** if anyone tells you, 'Look, here is the Messiah,' or 'There he is,' don't believe it.
> 
> Mat 24:24 NLT - For **false messiahs and false prophets will rise up and perform great signs and wonders so as to deceive, if possible, even God's chosen ones**.
> 
> Mat 24:25 NLT - See, I have warned you about this ahead of time.
> 
> Mat 24:26 NLT - "So if someone tells you, 'Look, the Messiah is out in the desert,' don't bother to go and look. Or, 'Look, he is hiding here,' don't believe it!
> 
> Mat 24:27 NLT - For as the lightning flashes in the east and shines to the west, so it will be when the Son of Man comes.
> 
> Mat 24:28 NLT - Just as the gathering of vultures shows there is a carcass nearby, so these signs indicate that the end is near.

#### Immediately After

- Sun Will Be Darkened
- Moon Will Give No Light
- Stars Fall From Sky
- Powers In Heaven Shaken

> Mat 24:29 NLT - "**Immediately after the anguish of those days**, the sun will be darkened, the moon will give no light, the stars will fall from the sky, and the powers in the heavens will be shaken.

Please **compare Matthew 24:29 with Revelation 6:12-14**.

> Rev 6:12 NLT - I watched as the Lamb broke **the sixth seal**, and there was a great earthquake. The sun became as dark as black cloth, and the moon became as red as blood.
> 
> Rev 6:13 NLT - Then the stars of the sky fell to the earth like green figs falling from a tree shaken by a strong wind.
> 
> Rev 6:14 NLT - The sky was rolled up like a scroll, and all of the mountains and islands were moved from their places.

#### THEN The Sign Of The Son Of Man

- Jesus' Sign Appears In The Heavens
- Global Deep Mourning On Earth
- Jesus Comes On The Clouds of Heaven
- Angels Sent Out At Trumpet Blast
- Chosen Ones Gathered From Heaven and Earth

> Mat 24:30 NLT - And **then at last, the sign that the Son of Man is coming will appear in the heavens**, and there will be deep mourning among all the peoples of the earth. And **they will see the Son of Man coming on the clouds of heaven with power and great glory.**
> 
> Mat 24:31 NLT - And he will send out his angels with the mighty blast of a trumpet, and they will gather his chosen ones from all over the world--from the farthest ends of the earth and heaven.

Luke 21:28 adds ...

> Luk 21:28 NLT - So **when all these things begin to happen**, stand and look up, for your salvation is near!"

[Part 1 - Jesus' End-Time Timeline - "What Sign Will Signal The End Of The World?"](https://benotdeceived.org/posts/series/jesus-end-time-timeline-part-1.html)

[Part 3 - Jesus' End-Time Timeline - "When Will All This Happen?"](https://benotdeceived.org/posts/series/jesus-end-time-timeline-part-3.html)
