---
title: Jesus' End-Time Timeline - When Will All This Happen ?
description: "Jesus' Response to the Disciples' 1st Question - When Will All This Happen?"  
date: 2017-10-24
categories: [End-Times Timeline, End of the World, Matthew 24, Signs]
---

## What Is Jesus' End-Time Timeline

### When Will All This Happen

This is part 3 of Jesus' End-Time Timeline as documented in Matthew 24. This article covers Jesus' response to the disciples' first question in Matthew 24:3 - "**When Will All This Happen?**"

#### When You See All These Things

- The Generation That Sees These Signs Begin, Will See ALL These Things Take Place

> Mat 24:32 NLT - "Now learn a lesson from the fig tree. When its branches bud and its leaves begin to sprout, you know that summer is near.
> 
> Mat 24:33 NLT - In the same way, **when you see all these things, you can know his return is very near, right at the door.**
> 
> Mat 24:34 NLT - I tell you the truth, this generation will not pass from the scene until all these things take place.
> 
> Mat 24:35 NLT - Heaven and earth will disappear, but my words will never disappear.

#### No One Knows the Day or Hour

- No Man Knows
- No Angel Knows
- Even Jesus Does Not Know
- ONLY The Father Knows

> Mat 24:36 NLT - "However, **no one knows the day or hour when these things will happen,** **not even the angels** in heaven **or the Son himself. Only the Father knows.**

#### Like The Days Of Noah

- Banquets, Parties, Weddings
- Two Men Working - One Taken, The Other Left
- Two Women Grinding - One Taken, The Other Left

> Mat 24:37 NLT - "**When the Son of Man returns**, it will be like it was in Noah's day.
> 
> Mat 24:38 NLT - In those days before the flood, the people were enjoying banquets and parties and weddings right up to the time Noah entered his boat.
> 
> Mat 24:39 NLT - People didn't realize what was going to happen until the flood came and swept them all away. **That is the way it will be when the Son of Man comes**.
> 
> Mat 24:40 NLT - "Two men will be working together in the field; one will be taken, the other left.
> 
> Mat 24:41 NLT - Two women will be grinding flour at the mill; one will be taken, the other left.

#### Multiple Warnings

- Keep Watch
- Understand This
- Be Ready All The Time

> Mat 24:42 NLT - "So you, too, must **keep watch**! For you don't know what day your Lord is coming.

Luke 21:34-36 adds ...

- Watch Out
- Don't Let Day Catch You Unaware
- That Day Comes Upon The Whole Earth
- Keep Alert
- Pray To Be Strong Enough To Escape And To Stand Before The Son of Man

> Luk 21:34 NLT - "**Watch out!** Don't let your hearts be dulled by carousing and drunkenness, and by the worries of this life**.** **Don't let that day catch you unaware**,
> 
> Luk 21:35 NLT - like a trap. For **that day will come upon everyone living on the earth**.
> 
> Luk 21:36 NLT - **Keep alert at all times**. And **pray that you might be strong enough to escape these coming horrors and stand before the Son of Man**."

> Mat 24:43 NLT - **Understand this**: If a homeowner knew exactly when a burglar was coming, he would keep watch and not permit his house to be broken into.
> 
> Mat 24:44 NLT - You also must **be ready all the time**, for the Son of Man will come when least expected.
> 
> Mat 24:45 NLT - "A faithful, sensible servant is one to whom the master can give the responsibility of managing his other household servants and feeding them.
> 
> Mat 24:46 NLT - If the master returns and finds that the servant has done a good job, there will be a reward**.**
> 
> Mat 24:47 NLT - I tell you the truth, **t**he master will put that servant in charge of all he owns**.**
> 
> Mat 24:48 NLT - But what if the servant is evil and thinks, 'My master won't be back for a while,'
> 
> Mat 24:49 NLT - and he begins beating the other servants, partying, and getting drunk?
> 
> Mat 24:50 NLT - The master will return unannounced and unexpected,
> 
> Mat 24:51 NLT - and he will cut the servant to pieces and assign him a place with the hypocrites. In that place there will be weeping and gnashing of teeth.

This concludes the 3 part series of Jesus' End-Time Timeline.

[Part 1 - Jesus' End-Time Timeline - "What Sign Will Signal The End Of The World?"](http://benotdeceived.org/jesus-end-time-timeline-part-1/) [Part 2 - Jesus' End-Time Timeline - "What Sign Will Signal Your Return?"](http://benotdeceived.org/jesus-end-time-timeline-part-2/)
