project:
    title: Be Not Deceived
    type: website
#    resources:
#        - "*.pdf"


website:
    title: "Be Not Deceived"
    favicon: images/favicon.ico
    site-url: "benotdeceived.org"
    description: "Dedicated to helping believers 'be not deceived' according to Jesus' command in Matthew 24:4."
    page-navigation: true
    search:
        location: sidebar
        type: textbox


    navbar:
        left:
            - text: Home
              href: index.qmd
            - text: Blog
              href: blog.qmd
            - text: Series
              href: series.qmd
            - text: Bible Study Notebook
              href: notebook/introduction.qmd
        right:
            - text: About
              href: about.qmd
            - archive.qmd
            - icon: rss
              text: RSS Feed
              href: blog.xml


    sidebar:
        header: "[Be Not Deceived](https::/benotdeceived.org)"
        collapse-level: 1
        align: left
        pinned: true
        border: true
        contents:
            - section: Home
              contents:
                - index.qmd

            - section: About
              contents:
                - href: about.qmd
                    
            - section: Blog
              contents:
                - href: blog.qmd
                -  href: archive.qmd
                    
                - section: Jesus' Endtime Timeline
                  contents:
                      - href: series.qmd
                      - href: posts/series/jesus-end-time-timeline-part-1.qmd
                      - href: posts/series/jesus-end-time-timeline-part-2.qmd
                      - href: posts/series/jesus-end-time-timeline-part-3.qmd

                - section: Gospel of John
                  contents:
                      - href: john.qmd
                      - href: posts/john/john.1.1-5.qmd  

            - section: Bible Study Notebook
              contents:
                  - href: notebook.qmd

                  - section: New Believer Introduction
                    contents:
                        - href: notebook/introduction.qmd
                          
                  - section: Foundations
                    contents:
                        - href: notebook/foundations/why.qmd
                        - href: notebook/foundations/bible.qmd
                        - href: notebook/foundations/god.qmd
                        - href: notebook/foundations/jesus.qmd
                        - href: notebook/foundations/holy-spirit.qmd
                        - href: notebook/foundations/salvation.qmd


    page-footer:
        right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
        center: "Copyright 2017-2022, [Be Not Deceived](https://benotdeceived.org)"
        left: 
            - text: "License"
              href: license.qmd
            - text: "Privacy Policy"
              href: privacy.qmd
            - text: "Cookie Policy"
              href: cookies.qmd
            - text: "Contact"
              href: contact.qmd

#    cookie-consent: implied


# Table of content settings
toc: true
toc-title: Table of Contents
toc-depth: 3


format:
    html:
        theme:	zephyr
        css: styles.css
        toc: true
        link-external-icon: true
        link-external-newwindow: true

#    pdf:
#        toc: true


callout-icon: false