project:
    title: Be Not Deceived
    type: website
#    resources:
#        - "*.pdf"


website:
    title: "Be Not Deceived"
    favicon: images/favicon.ico
    site-url: "benotdeceived.org"
    description: "Dedicated to helping believers 'be not deceived' according to Jesus' command in Matthew 24:4."
    page-navigation: true
    search:
        location: sidebar
        type: textbox


    navbar:
        left:
            - text: Home
              href: index.qmd
            - text: Blog
              href: blog.qmd
            - text: Series
              href: series.qmd
            - text: Bible Study Notebook
              href: notebook.qmd
        right:
            - text: About
              href: about.qmd
            - archive.qmd
            - icon: rss
              text: RSS Feed
              href: blog.xml


    sidebar:
        header: Be Not Deceived
        pinned: true
        align: left
        border: true
        collapse-level: 1
        contents:
            - section: Home
              contents:
                  - href: index.qmd

            - section: About
              contents:
                  - href: about.qmd

            - section:  Blog
              contents:
                - href: blog.qmd
                - href: archive.qmd

            - section: Series
              contents:
                - text: Series Index
                  href: series.qmd
                - text: "Jesus' End-Time Timeline - What Sign Will Signal the End of the World"
                  href: https://benotdeceived.org/posts/series/jesus-end-time-timeline-part-1.html
                - text: "Jesus' End-Time Timeline - What Sign Will Signal Your Return"
                  href: https://benotdeceived.org/posts/series/jesus-end-time-timeline-part-2.html
                - text: "Jesus' End-Time Timeline - When Will All This Happen"
                  href: https://benotdeceived.org/posts/series/jesus-end-time-timeline-part-3.html

            - section: Bible Study Notebook
              contents:
                - href: notebook.qmd


    page-footer:
        right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
        center: "Copyright 2017-2022, [Be Not Deceived](https://benotdeceived.org)"
        left: 
            - text: "License"
              href: license.qmd
            - text: "Privacy Policy"
              href: privacy.qmd
            - text: "Cookie Policy"
              href: cookies.qmd
            - text: "Contact"
              href: contact.qmd

#    cookie-consent: implied


# Table of content settings
toc: true
toc-title: Table of Contents
toc-depth: 3


format:
    html:
        theme:	zephyr
        css: styles.css
        toc: true
        link-external-icon: true
        link-external-newwindow: true

#    pdf:
#        toc: true


callout-icon: false