---
page-layout: full
# Table of content settings
toc: true
toc-title: Table of Contents
toc-depth: 3
format:
    html:
        include-after-body: footer.html
---

# "Welcome to Be Not Deceived"
> For false christs and false prophets ... would deceive even the elect, if that were possible. -- Matthew 24:24  

<br />

---

## Why 'Be Not Deceived'

Jesus warned us to 'Be Not Deceived'.  Why was it so important to Him that He repeated it often?  The reason can be found in Matthew 24:24  ...

> For false messiahs and false prophets will rise up and perform great signs and wonders **so as to deceive, if possible, even God's chosen ones**. Matt 24:24

My goal is to help as many people as possible to 'Be Not Deceived'!

### We Are Part Of The Problem

I am finding that each of us comes to the table with our predispositions and preconceived ideas.

Recently, God is showing me there are things in His Word I never saw before.  There are also things that I thought were in the Bible, that are not there.

Now, when I read or study the Word, I ask Him that I would "be not deceived".  I renounce my preconceived ideas and predispositions.  I ask Him to open my understanding to what His Word actually says as opposed to what I've been taught, or believe, it says.

> Jas 1:5 NLT – **If you need wisdom, ask our generous God, and he will give it to you**. He will not rebuke you for asking.

### Others Are Part of the Problem

Again, Jesus repeatedly told us ...

> Mat 24:24 NLT - **For false messiahs and false prophets will rise up and perform great signs and wonders so as to deceive**, if possible, even God's chosen ones.

We should not be surprised at the many so-called Bible teachers and preachers who mishandle the Scriptures and deceive so many people today.  Jesus told us it would be so.  So the question is "How can we 'Not Be Deceived'?

### "How to 'Not Be Deceived'?

We do not need these false teachers or preachers, or anyone else, to teach us what the Bible says or doesn’t say.

Let me lay some groundwork for this last statement.

#### Jesus Is the New Covenant

The Book of Isaiah tells us that the Father gave Jesus as His \[second\] Covenant with Israel ...

> Isa 49:8 NLT - This is what the LORD says: "At just the right time, I will respond to you. On the day of salvation I will help you. **I will** protect you and **give you to the people as my covenant with them**. Through you I will reestablish the land of Israel and assign it to its own people again.

#### We Are Grafted Into Israel

As a blood-bought, born-again Christian, you have been grafted into the natural olive tree of Israel ...

> Rom 11:17 NLT - But some of these branches from Abraham's tree--some of the people of Israel--have been broken off. **And you Gentiles**, who were branches from a wild olive tree, **have been grafted in. So now you also receive the blessing God has promised Abraham and his children, sharing in the rich nourishment from the root of God's special olive tree.**

#### Characteristics Of The New Covenant

What are some of the characteristics of this New Covenant?

> Heb 8:8 NLT - But when God found fault with the people, he said: "**The day is coming**, says the LORD, **when I will make a new covenant with the people of Israel and Judah**.
> 
> Heb 8:9 NLT - This covenant will not be like the one I made with their ancestors when I took them by the hand and led them out of the land of Egypt. They did not remain faithful to my covenant, so I turned my back on them, says the LORD.
> 
> Heb 8:10 NLT - But **this is the new covenant** I will make with the people of Israel on that day, says the LORD: **I will put my laws in their minds, and I will write them on their hearts. I will be their God, and they will be my people.**
> 
> Heb 8:11 NLT - And **they will not need to teach their neighbors, nor will they need to teach their relatives, saying, 'You should know the LORD.' For everyone, from the least to the greatest, will know me already.**
> 
> Heb 8:12 NLT - And I will forgive their wickedness, and I will never again remember their sins."

#### Can We Discern His Voice?

Jesus, Himself, told us ...

> Jhn 10:3 NLT - The gatekeeper opens the gate for him, and **the sheep recognize his voice and come to him. He calls his own sheep by name** and leads them out.
> 
> Jhn 10:4 NLT - After he has gathered his own flock, he walks ahead of them, and **they follow him because they know his voice.**
> 
> Jhn 10:5 NLT - **They won't follow a stranger; they will run from him because they don't know his voice**."

He also told us ...

> Jhn 14:26 NLT - But when the Father sends the Advocate as my representative--that is, **the Holy Spirit**\--he **will teach you everything and will remind you of everything I have told you**.

#### How to Discern His Voice

Now let me ask you, how do you recognize the voice of your wife or husband? your parents or children?

You recognize their voices because you have spent time with them.  You live with them, and share experiences with them. You do not have to see them to recognize their voices.

The same thing is true with Jesus. You need to spend time with Him in prayer and in His Word. The Holy Spirit then begins teaching you how He thinks; how He feels; what He would do in a given situation.

If you do not spend time with Him, or in His Word, you cannot expect to know Him.  If you do not come to know Him, you will be deceived.  You will not only be deceived by false prophets and teachers, but by the ultimate deception of all - the Antichrist.

So, my brothers and sisters, I challenge you to spend time with the Lord and in His Word.  So much so that when someone says that something is in the Word that isn't you will 'Be Not Deceived'.

#### My Prayer Is That You Be Not Deceived

Father God, I ask that You would touch the heart of every person whom You bring to this blog. I ask they become so hungry to intimately know You, and Your Word. I pray they would continually pray ... "Father, help me to 'Be Not Deceived'!" Thank You, Father, in Jesus' Name. Amen.
