---
date: 2022-11-25
categories: [Translation Copyrights]
---

# Translations and Copyrights

---

## Default Translation Used By Be Not Deceived

### BSB - [Berean Standard Bible](https://bereanbible.com/)

Unless otherwise noted, all Scripture references are from the [Berean Standard Bible](https://bereanbible.com).

The Holy Bible, [Berean Standard Bible](https://bereanbible.com/), BSB
Copyright ©2016, 2020 by Bible Hub
Used by Permission. All Rights Reserved Worldwide.

## Other Translations

### BLB - [Berean Literal Bible](https://literalbible.com/)

The Holy Bible, Berean Literal Bible, BLB
Copyright ©2016, 2020 by Bible Hub
Used by Permission. All Rights Reserved Worldwide.

### AMPC - Amplified Bible Classic

Scripture quotations taken from the Amplified® Bible (AMPC),
Copyright © 1954, 1958, 1962, 1964, 1965, 1987 by The Lockman Foundation
Used by permission. [Lockman Foundation](https://www.lockman.org)

### KJV - King James Version

This Bible is in the Public Domain.

### NASB - New American Standard Bible
Scripture is taken from the NEW AMERICAN STANDARD BIBLE(r), Copyright (c) 1960,1962,1963,1968,1971,1972,1973,1975,1977 by The Lockman Foundation. Used by permission. [Lockman Foundation](https://www.lockman.org).

### WET - Kenneth S. Weust - The New Testament - An Expanded Translation

#### VOLUME I, THE GOSPELS

Copyright Wm. B. Eerdmans Publishing Company 1956;
Copyright renewed 1984 Jeannette J. Wuest

#### VOLUME II, ACTS THROUGH EPHESIANS

Copyright Wm. B. Eerdmans Publishing Company 1958

#### VOLUME III, PHILIPPIANS THROUGH THE REVELATION

Copyright Wm. B. Eerdmans Publishing Company 1959

