---
title: Who Is The Holy Spirit
date: 2022-12-12
date-modified: last-modified
categories: [Holy Spirit]
---

---

## So - Who Is This Holy Spirit?

* He is the Spirit of God

:::{.callout-scripture}
# 1 Corinthians 2:10-11  

10 But God has revealed it to us by the Spirit.  The Spirit searches all things, even the deep things of God.  
11 For who among men knows the thoughts of man except his own spirit within him?  So too, no one knows the thought of God except the Spirit of God.  
:::

* He dwells in us

:::{.callout-scripture}
# 1 Corinthians 3:16  

16 Do you not know that you yourselves are God's temple, and that God's Spirit dwells in you?  
:::

* He is the Spirit of God's Son, Jesus

:::{.callout-scripture}
# Galatians 4:6  

6 And because you are sons, God sent the Spirit of His Son into our hearts, crying out, "Abba, Father!"  
:::

### Is The Holy Spirit God?

* One God, Three Persons
	* God the Father
	* God the Son
	* God the Holy Spirit

:::{.callout-scripture}
# Matthew 28:19  

19 Therefore go and make disciples of all nations, baptizing them in the name of the Father, and of the Son, and of the Holy Spirit.  
:::

:::{.callout-scripture}
# 2 Corinthians 13:14  

14 The grace of the Lord Jesus Christ, and the love of God, and the fellowship of the Holy Spirit be with all of you.  
:::

### Is The Holy Spirit a "Person" or a Spiritual "Influence"?

* He is a Person
	* Our Helper [Advocate] and Teacher

:::{.callout-scripture}
# John 14:26  

26 But the Advocate, the Holy Spirit, whom the Father will send in My name, will teach you all things and will remind you of everything I have told you.  
:::

* He Speaks to Us

:::{.callout-scripture}
# Acts 1:16  

16 Brothers, the Scripture had to be fulfilled which the Holy Spirit foretold through the mouth of David concerning Judas, who became a guide for those who arrested Jesus.
:::

* He is the Spirit of Truth
* He Guides Us
* He Speaks to Us
* He Hears
* He Reveals What Is Coming in the Future

:::{.callout-scripture}
# John 16:13  

13 However, when the Spirit of truth comes, He will guide into all truth.  For we will not speak on His own, but He will speak what He hears, and He will declare to you what is to come.
:::
