---
title: The Bible - God-Breathed
date: 2022-12-12
date-modified: last-modified
categories: [The Bible, Divine Revelation, Authority of Scripture]
---

---

God's Divine Revelation has been manifested in two ways.

* The Bible - the written Word of God 
*  Jesus, who the Scriptures call "The Word"

## The Bible - God's Written Revelation To Man

### Is 'God-Breathed' And For Our Instruction

:::{.callout-scripture}
# 2 Timothy 3:16-17  

16 **All** Scripture is God-breathed and is **useful for instruction, for conviction, for correction, and for training in righteousness**,  
17 so that the **man of God may be complete, fully equipped for every good work**.
:::

*"God-breathed"* means *"inspired by God"*.  

:::{.callout-word-study}
# **Strong's G2315 *theopneustos***  

**HELPS Word-studies** [Source](https://biblehub.com/greek/2315.htm)  

2315 *theópneustos* (from 2316 */theós*, "God" and 4154 */pnéō*, "breathe out") – **properly, God-breathed, referring to the divine inspiration (inbreathing) of Scripture** (used only in 2 Tim 3:16).  

2315 */theópneustos* ("God-breathed"), likely a term coined by Paul, **"expresses the sacred nature of the Scriptures (their divine origin) and their power to sanctify believers" **(C. Spicq, 2, 193).  

[Inbreathing (2315 */theópneustos*) **relates directly to God's Spirit (Gk pneuma) which can also be translated "breath."**]  

*2 Tim 3:16: "Each-and-every (3956 /pás, singular) Scripture (Gk, singular) is God-breathed (2315 */theópneustos*) and profitable for teaching, for convincing, for correction, for training in righteousness."  *

**The singular (*anarthrous*) use of 3956 */pás* ("all") underlines that each part of speech (every inflected word-form, "reflex") used in the Bible is God-breathed, i.e. inscripturated (written) under divine inspiration.**


[G. Archer, "2315 **(*theópneustos*) is better rendered '*breathed out by God*' as the emphasis is upon the divine origin of the inscripturated revelation itself**" (A Survey of OT Introduction, fn. 7, 29).]
:::

## Jesus - The Word

:::{.callout-scripture}
# Revelation 19:13  

13 He is dressed in a robe dipped in blood, and **His name is The Word of God.**  
:::

### Jesus is Both God and Man

:::{.callout-scripture}
# John 1:1-4, 14

1 **In the beginning was the Word**, and **the Word was God**.  
2 He was with God in the beginning.  
3 Through Him all things were made, and without Him nothing was made that has been made.  
4 In Him was life, and that life was the light of men.  
...  
14 **The Word became flesh and made His dwelling among us**. We have seen His glory, the glory of the one and only Son from the Father, full of grace and truth.  
:::

## **How Should We Study The Scriptures**

### With Reverence

:::{.callout-scripture}
# 2 Timothy 2:15  

15 Make every effort to present yourself approved to God, an unashamed workman **who accurately handles the word of truth**.
:::

:::{.callout-scripture}
# Hebrews 12:25  

25 **See to it that you do not refuse Him who speaks.** For if the people did not escape when they refused Him who warned them on earth, how much less will we escape if we reject Him who warns us from heaven.?
:::

### Meditate On It

:::{.callout-scripture}
# Joshua 1:8  

8 This Book of the Law must not depart from your mouth; meditate on it day and night, so that you may be careful to do everything written in it.  For then you will prosper and succeed in all you do.

### Believe It

:::{.callout-scripture}
# Ephesians 1:13-14  

13 And in Him, having heard and believed the word of truth -- the gospel of your salvation - you were sealed with the promised Holy Spirit,   
14 who is the pledge of our inheritance until the redemption of those who are God's possession, to the praise of His glory.
:::

### Receive It In Humility

:::{.callout-scripture}
# James 1:21  

21 Therefore, get rid of all moral filth and every expression of evil, and **humbly accept the word planted in you, which can save your souls**.
:::

### With Gratitude

:::{.callout-scripture}
# Colossians 3:16  

16 **Let the word of Christ richly dwell within you** as you teach and admonish one another with all wisdom, and as you sing psalms, hymns, and spiritual songs **with gratitude in your hearts to God**.
:::

### With Eagerness and Diligent Study

:::{.callout-scripture}
# Acts 17:11  

11 Now the Bereans were more noble-minded than the Thessalonians, for they **received the message with great eagerness and examined the Scriptures every day to see if these teachings were true.**
:::

### By Being A Doer Not Just A Hearer

:::{.callout-scripture}
# James 1:22  

22 **Be doers of the word, and not hearers only**. Otherwise, you are deceiving yourselves.
:::

:::{.callout-scripture}
# Luke 11:28  

28 But He replied, "Blessed rather are those who hear the word of God **and obey it**."
:::

:::{.callout-scripture}
# John 3:21  

21 But **whoever practices the truth comes into the Light**, so that it may be seen clearly that what he has done has been accomplished in God.
:::

:::{.callout-scripture}
# Matthew 7:21, 24-25  

21 Not everyone who says to Me, 'Lord, Lord,' will enter the kingdom of heaven, but only **he who does the will of My Father in heaven**.  
...  
24 Therefore everyone who hears these words of Mine **and acts on them** is like a wise man who built his house on the rock.  
25 The rain fell, the torrents raged, and the winds blew and beat against that house; yet it did not fall, because its foundation was on the rock.
:::

### By Holding It Fast

:::{.callout-scripture}
# 1 Corinthians 15:1-2  

1 Now, brothers, I want to remind you of the gospel I preached to you, which **you received, and in which you stand firm.**  
2 **By this gospel you are saved, if you hold firmly to the word I preached to you. Otherwise, you have believed in vain.**
:::

